apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: likhitha-pvc
  namespace: app-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client   
  resources:
    requests:
      storage: 10Gi